### ISSUE TITLE
关于实验结果

### ISSUE THREAD

**Issue by ownnaruto** [XDZhelheim/Torch-MTS#16]
你好，现在这版代码 logs 中的实验结果可以直接使用吗？

**Comment by XDZhelheim** [comment]
依然是bug版本的残留，不建议用。接下来一个月的主要更新内容就是重跑所有模型重新写大表。

如果急需，麻烦手动重跑一下吧。现在代码是对的，直接跑就可以。

**Comment by XDZhelheim** [comment]
模型的超参是一致的。学习率很多模型我调过，尤其是 milestones (scheduler的重点参数)。

最麻烦的是有些模型官方只有LABAY，没有4个PEMS (比如21年之前的几个)，这种基本是照抄的LABAY的参数，同时我也参考了BasicTS。https://github.com/zezhishao/BasicTS/tree/master/baselines

还有一点需要特别注意的地方就是PEMS的loss我这用的是HuberLoss (默认情况=SmoothedL1Loss)，而不是MaskMAE。我这测出来的结果是huber更好，所以就一直用了。还是刚才说的问题，有的官方没PEMS，所以没有确定的标准，如果官方写明用哪个loss了，那最好还是一致。后续的版本更新我会重点关注这个设置，有官方就按官方。

怎么设置用哪个loss的例子:
```
<xxx.yaml>

METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12

  loss: mask_mae <------ here
```
能用哪些loss: `lib/losses.py`
